src/Account/urls.py
from django.urls import path
from .views import *

app_name = 'Account'
urlpatterns = [
    path('signup', account_creation, name='creation'),
    path('login', user_login, name='login'),
    path('logout', user_logout, name='logout'),
    path('update/<int:user_id>/', update_account, name='update'),
    path('display', users_display, name='display'),
    path('update_admin/<int:user_id>/', user_update_admin, name='update_admin'),
    path('update_archive/<int:user_id>/', user_update_archive, name='update_archive'),
    path('events/<int:user_id>/', user_events_display, name="events"),

]

src/CollegeBook/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.triggers.cron import CronTrigger
from Event.tasks import check_event_is_archived, send_remainders_mail, send_thanks_mail, check_rep_is_archived

from . import settings

urlpatterns = [
                  path('', include("Event.urls")),
                  path('admin/', admin.site.urls),
                  path('account/', include("Account.urls")),
                  path('configuration/', include("Configuration.urls")),
                  path('reservation/', include("Reservation.urls")),
                  path('payment/', include("Payment.urls")),
                  path('validation/', include('Validation.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

print("setup tasks")
scheduler = BackgroundScheduler()
scheduler.add_job(check_rep_is_archived, CronTrigger.from_crontab('* * * * *'))
scheduler.add_job(check_event_is_archived, CronTrigger.from_crontab('* * * * *'))  # Exécute toutes les minutes
scheduler.add_job(send_remainders_mail, CronTrigger.from_crontab('0 2 * * *'))  # Exécute toutes les minutes
scheduler.add_job(send_thanks_mail, CronTrigger.from_crontab('0 2 * * *'))  # Exécute toutes les minutes
scheduler.start()

src/Configuration/urls.py
from django.urls import path
from .views import *

app_name = 'Config'
urlpatterns = [
    path('', area_configuration, name="Configuration"),
    path('create_json/', create_json, name="create_json"),
    path('get_place_types/<str:config_name>/', get_place_types, name="get_place_types"),
]

src/Event/urls.py
from django.urls import path
from .views import *

app_name = 'Event'
urlpatterns = [
    path('', events_display, name='display'),
    path('details/<int:even_id>/', event_details, name='details'),
    path('creation/', event_creation, name='creation'),
    path('delete_representation/<int:representation_id>/', delete_representation, name="delete_representation"),
    path('update_event/<int:event_id>/', event_update, name='update'),
    path('publish_event/<int:event_id>/', publish_event, name='publish_event'),
    path('delete_event_draft/<int:event_id>/', delete_event_draft, name='delete_draft')
]

src/CollegeBook/templates/default.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--  Font Noto Bold -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans:wght@400;600;700&display=swap" rel="stylesheet">
    <!--  Font Poppins  /  Manrope  / Montserrat  -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Manrope&family=Montserrat&family=Poppins:ital@1&display=swap" rel="stylesheet">
    <!--  -->

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@yaireo/tagify"></script>
    <link href="https://cdn.jsdelivr.net/npm/@yaireo/tagify/dist/tagify.css" rel="stylesheet" type="text/css"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@yaireo/tagify@3.1.0/dist/tagify.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/habibmhamadi/multi-select-tag/dist/css/multi-select-tag.css">
    <link rel="stylesheet" href= {% static  "css/Style.css" %} >
    <title>CollegeSite</title>
    {% block head %}
    {% endblock %}
</head>
<body>
    <header>
        <nav class="nav-bar">
            <div>
                <a href="{% url 'Event:display' %}" draggable="false">
                    <img src= {% static "img/CSPU.png" %} class="logo" draggable="false">
                </a>
            </div>
            <div class="links">
                {% if user.is_authenticated %}
                <ul class="nav-ul">
                    <li><a href="{% url 'Event:display' %}" class="nav-a" id="nav-events">Événements</a></li>
                    {% if user.is_staff %}
                    <li><a href="{% url 'Account:display' %}" class="nav-a" id="nav-admins">Admins</a></li>
                    <li><a href="{% url 'Account:creation' %}" class="nav-a" id="nav-create-account">Créer un compte</a></li>
                    {% endif %}
                    <li><a href="{% url 'Event:creation' %}" class="nav-a" id="nav-create-event">Créer un événement</a></li>
                    <li><a href="{% url 'Config:Configuration' %}" class="nav-a" id="nav-create-config">Créer une configuration</a></li>
                    <li><a href="{% url 'Account:events' user.id %}" class="nav-a" id="nav-personnal-events">Vos événements</a></li>
                    <li><a href="{% url 'Account:logout' %}" class="nav-a" id="nav-logout">Se déconnecter</a></li>
                    <li><a href="{% url 'Account:update' user.id %}" class="nav-a" id="nav-account">Compte</a></li>
                </ul>
                {% else %}
                <ul class="nav-ul">
                    <li><a href="{% url 'Event:display' %}" class="nav-a" id="nav-events">Événements</a></li>
                    <li><a href="{% url 'Account:login' %}" class="nav-a" id="nav-login">Se connecter</a></li>
                </ul>
                {% endif %}
            </div>
            <div class="menu">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-list" viewBox="0 0 16 16">
                  <path fill-rule="evenodd" d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"/>
                </svg>
            </div>
        </nav>
    </header>

    <div class="content">
        {% block body %}
        {% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script>
        flatpickr("input[class=MultiDate]", {mode:"multiple", enableTime:true, time_24hr:true, dateFormat:"d-m-Y/H:i"});
        flatpickr("input[class=Time]", {enableTime: true, noCalendar: true, dateFormat: "H:i", time_24hr: true});
    </script>
    <script src="https://cdn.jsdelivr.net/npm/@yaireo/tagify"></script>
    <script src="https://cdn.jsdelivr.net/npm/@yaireo/tagify/dist/tagify.polyfills.min.js"></script>
{#    <script src="//code.jquery.com/jquery.min.js"></script>#}
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.4.1/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@yaireo/tagify@3.1.0/dist/tagify.min.js"></script>
    <script src="https://cdn.jsdelivr.net/gh/habibmhamadi/multi-select-tag/dist/js/multi-select-tag.js"></script>
    <script src="{% static 'js/Base.js' %}"></script>
    {% block script %}
    {% endblock %}
</body>
</html>

src/CollegeBook/templates/error.html
{% extends "default.html" %}

{% block body %}
<h1 class="title">Erreur : {{ error }} </h1>
{% endblock %}