src/Account/urls.py
from django.urls import path
from .views import *

app_name = 'Account'
urlpatterns = [
    path('signup', account_creation, name='creation'),
    path('login', user_login, name='login'),
    path('logout', user_logout, name='logout'),
    path('update/<int:user_id>/', update_account, name='update'),
    path('display', users_display, name='display'),
    path('update_admin/<int:user_id>/', user_update_admin, name='update_admin'),
    path('update_archive/<int:user_id>/', user_update_archive, name='update_archive'),
    path('events/<int:user_id>/', user_events_display, name="events"),

]

src/CollegeBook/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.triggers.cron import CronTrigger
from Event.tasks import check_event_is_archived, send_remainders_mail, send_thanks_mail, check_rep_is_archived

from . import settings

urlpatterns = [
                  path('', include("Event.urls")),
                  path('admin/', admin.site.urls),
                  path('account/', include("Account.urls")),
                  path('configuration/', include("Configuration.urls")),
                  path('reservation/', include("Reservation.urls")),
                  path('payment/', include("Payment.urls")),
                  path('validation/', include('Validation.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

print("setup tasks")
scheduler = BackgroundScheduler()
scheduler.add_job(check_rep_is_archived, CronTrigger.from_crontab('* * * * *'))
scheduler.add_job(check_event_is_archived, CronTrigger.from_crontab('* * * * *'))  # Exécute toutes les minutes
scheduler.add_job(send_remainders_mail, CronTrigger.from_crontab('0 2 * * *'))  # Exécute toutes les minutes
scheduler.add_job(send_thanks_mail, CronTrigger.from_crontab('0 2 * * *'))  # Exécute toutes les minutes
scheduler.start()

src/Event/urls.py
from django.urls import path
from .views import *

app_name = 'Event'
urlpatterns = [
    path('', events_display, name='display'),
    path('details/<int:even_id>/', event_details, name='details'),
    path('creation/', event_creation, name='creation'),
    path('delete_representation/<int:representation_id>/', delete_representation, name="delete_representation"),
    path('update_event/<int:event_id>/', event_update, name='update'),
    path('publish_event/<int:event_id>/', publish_event, name='publish_event'),
    path('delete_event_draft/<int:event_id>/', delete_event_draft, name='delete_draft')
]

src/Account/models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.core.mail import send_mail
from django.db import models


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Creates and saves a User with the given email and password.
        """
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.last_name = "Admin"
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_staff', True)

        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(('Adresse email'), unique=True)
    first_name = models.CharField(('Prénom'), max_length=30, blank=True)
    last_name = models.CharField(('Nom de famille'), max_length=30, blank=True)
    date_joined = models.DateTimeField(('Date de création'), auto_now_add=True)
    last_login = models.DateTimeField(('Dernier login'), auto_now_add=True, null=True)
    is_active = models.BooleanField(('Actif'), default=True)
    is_staff = models.BooleanField(('SuperAdmin'), default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'user'
        verbose_name_plural = 'users'

    def get_full_name(self):
        """
        Returns the first_name plus the last_name, with a space in between.
        """
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        """
        Returns the short name for the user.
        """
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """
        Sends an email to this User.
        """
        send_mail(subject, message, from_email, [self.email], **kwargs)

    def __str__(self) -> str:
        """
        Show the email when printed
        """
        return self.email

    def update_is_staff_superuser(self):
        self.is_staff = not self.is_staff
        self.is_superuser = not self.is_superuser

    def update_is_active(self):
        self.is_active = not self.is_active

src/Account/forms.py
from django import forms

from .models import User
from CollegeBook.utils import check_password


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'email',
            'password',
            'is_staff',
        ]
        labels = {'first_name': 'Prénom', 'last_name': 'Nom', 'email': 'Email', 'password': 'Mot de passe',
                  'is_staff': 'Super Admin'}
        widgets = {'password': forms.PasswordInput}

    confirm_password = forms.CharField(label='Confirmer le mot de passe', max_length=50, required=True,
                                       widget=forms.PasswordInput)

    def clean_confirm_password(self):
        check_password(self)

    def save(self, commit=True):
        user = super(UserForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password'])
        user.username = self.cleaned_data['email']
        if commit:
            user.save()
        return user


class LoginUserForm(forms.Form):
    email = forms.CharField(label='Email', max_length=50, required=True)
    password = forms.CharField(label='Mot de passe', max_length=50, required=True, widget=forms.PasswordInput)


class UpdateUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'email',
        ]
        labels = {'first_name': 'Prénom', 'last_name': 'Nom', 'email': 'Email'}

src/Account/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test
from django.shortcuts import render, redirect
from django.db.models import Q

from Account.forms import UserForm, LoginUserForm, UpdateUserForm
from Account.models import User
from Event.models import Representation, Event


@user_passes_test(lambda u: u.is_active and u.is_staff)
def account_creation(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('Account:display')
    else:
        form = UserForm()

    return render(request, 'account_creation.html', {'form': form})


def user_login(request):
    if request.method == 'POST':
        form = LoginUserForm(request.POST)
        if form.is_valid():
            user = authenticate(request, username=request.POST['email'], password=request.POST['password'])
            if user is not None and user.is_active:
                login(request=request, user=user)
                return redirect('Event:display')
    else:
        form = LoginUserForm()
    return render(request, 'login.html', {'form': form})


@login_required
def user_logout(request):
    logout(request)
    return redirect('Event:display')


@login_required
def update_account(request, user_id):
    user = User.objects.get(pk=user_id)
    if request.method == 'POST':
        form = UpdateUserForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            return redirect('Event:display')
    else:

        form = UpdateUserForm(instance=user)
    return render(request, 'update_account.html', {'form': form})


@user_passes_test(lambda u: u.is_active and u.is_staff)
def users_display(request):
    all_users = User.objects.all()
    return render(request, 'users_display.html', {'all_users': all_users})


@user_passes_test(lambda u: u.is_active and u.is_staff, login_url='')
def user_update_admin(request, user_id):
    user = User.objects.get(id=user_id)
    user.update_is_staff_superuser()
    user.save()
    return redirect('Account:display')


@user_passes_test(lambda u: u.is_active and u.is_staff, login_url='')
def user_update_archive(request, user_id):
    user = User.objects.get(id=user_id)
    user.update_is_active()
    user.save()
    return redirect('Account:display')


@login_required
def user_events_display(request, user_id):
    user_events_draft = Event.objects.filter(user=user_id,state='DRF')
    user_events = Event.objects.filter(~Q(state='DRF'), user=user_id )
    user_representations = list()
    user_representations_archived = list()
    for event in user_events:
        representations_ACT = Representation.objects.filter(event=event.id, state='ACT')
        representations_ARC = Representation.objects.filter(event=event.id, state='ARC')
        for representation in representations_ACT:
            user_representations.append(representation)
        for representation in representations_ARC:
            user_representations_archived.append(representation)
    return render(request, 'user_events_display.html', {'user_representations': user_representations,
                                                        'user_events_draft': user_events_draft,
                                                        'user_representations_archived': user_representations_archived})

src/Account/templates/account_creation.html
{% extends "default.html" %}

{% block body %}
    <h1 class="title"> Création de compte </h1>
    <div class="form">
        <form action="" method="post">
            {% csrf_token %}
            <div class="input-box">
                {{ form.first_name.label }}
                {{ form.first_name }}
                {{ form.first_name.errors }}
            </div>
            <div class="input-box">
                {{ form.last_name.label }}
                {{ form.last_name }}
                {{ form.last_name.errors }}
            </div>
            <div class="input-box">
                {{ form.email.label }}
                {{ form.email }}
                {{ form.email.errors }}
            </div>
            <div class="input-box">
                {{ form.password.label }}
                {{ form.password }}
                {{ form.password.errors }}
            </div>
            <div class="input-box">
                {{ form.confirm_password.label }}
                {{ form.confirm_password }}
                {{ form.confirm_password.errors }}
            </div>
            <div class="input-box">
                {{ form.is_staff.label }}
                {{ form.is_staff }}
                {{ form.is_staff.errors }}
            </div>
            <input type="submit" value="Créer le compte">
        </form>
    </div>
{% endblock %}

src/Account/templates/login.html
{% extends "default.html" %}

{% block body %}
    <h1 class="title">Connexion</h1>
    <div>
        <div class="form">
            <form action="" method="post">
                {% csrf_token %}
                <div class="input-box">
                    {{ form.email.label }}
                    {{ form.email }}
                    {{ form.email.errors }}
                </div>
                <div class="input-box">
                    {{ form.password.label }}
                    {{ form.password }}
                    {{ form.password.errors }}
                </div>
                <input type="submit" value="Se connecter">
            </form>
        </div>
    </div>
{% endblock %}

src/Account/templates/update_account.html
{% extends "default.html" %}

{% block body %}
    <h1 class="title">Modifier vos informations</h1>
    <div>
        <div class="form">
            <form action="" method="post">
                {% csrf_token %}
                <div class="input-box">
                    {{ form.first_name.label }}
                    {{ form.first_name }}
                    {{ form.first_name.errors }}
                </div>
                <div class="input-box">
                    {{ form.last_name.label }}
                    {{ form.last_name }}
                    {{ form.last_name.errors }}
                </div>
                <div class="input-box">
                    {{ form.email.label }}
                    {{ form.email }}
                    {{ form.email.errors }}
                </div>
                <input type="submit" value="Modifier le compte">
            </form>
        </div>
    </div>
    
{% endblock %}

src/Account/templates/user_events_display.html
{% extends "default.html" %}

{% load static %}

{%  block head %}
    <link rel="stylesheet" href= {% static "css/Account.css" %} >

{% endblock %}

{% block body %}
    <h1 class="title">Vos événements</h1>

        <div class="tabs">
            <a data-tab-value="#tab_1" class="button active">Brouillons</a>
            <a data-tab-value="#tab_2" class="button">À venir</a>
            <a data-tab-value="#tab_3" class="button">Passés</a>
        </div>

        <div class="tab-content">
            <div class="tabs__tab active" id="tab_1" data-tab-info>
                <table class="table">
                    <thead>
                    <tr>
                        <td>Nom événement</td>
                        <td>Modifier le brouillon</td>
                        <td>Publier l'événement</td>
                        <td>Supprimer le brouillon</td>
                    </tr>
                    </thead>
                    <tbody>
                    {% for event in user_events_draft %}
                        <tr>
                            <td data-label="Nom événement">{{ event.name }}</td>
                            <td data-label="Modifier le brouillon"><a class="table-svg ok" href="{% url 'Event:update' event.id %}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                                    <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                                    <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                                </svg>
                            </a></td>
                            <td data-label="Publier l'evenement"><a class="table-svg ok" href="{% url 'Event:publish_event' event.id %}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-check2-square" viewBox="0 0 16 16">
                                      <path d="M3 14.5A1.5 1.5 0 0 1 1.5 13V3A1.5 1.5 0 0 1 3 1.5h8a.5.5 0 0 1 0 1H3a.5.5 0 0 0-.5.5v10a.5.5 0 0 0 .5.5h10a.5.5 0 0 0 .5-.5V8a.5.5 0 0 1 1 0v5a1.5 1.5 0 0 1-1.5 1.5H3z"/>
                                      <path d="m8.354 10.354 7-7a.5.5 0 0 0-.708-.708L8 9.293 5.354 6.646a.5.5 0 1 0-.708.708l3 3a.5.5 0 0 0 .708 0z"/>
                                    </svg>
                                </a></td>
                            <td data-label="Supprimer le brouillon"><a class="table-svg ok" href="{% url 'Event:delete_draft' event.id %}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-circle" viewBox="0 0 16 16">
                                    <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                                    <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                                </svg>
                            </a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>



            <div class="tabs__tab" id="tab_2" data-tab-info>
                <table class="table">
                    <thead>
                    <tr>
                        <td>Nom événement</td>
                        <td>Date</td>
                        <td>Annuler</td>
                    </tr>
                    </thead>
                    <tbody>

                    {% for representation in user_representations %}
                        <tr>
                            <td data-label="Nom événement"><a class="link" href="{% url 'Event:details' representation.event.id %}">{{ representation.event.name }}</a></td>
                            <td data-label="Date">{{representation.date}}</td>
                            <td data-label="Annuler"><a class="table-svg ok" href="{% url 'Event:delete_representation' representation.id %}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-circle" viewBox="0 0 16 16">
                                    <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                                    <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                                </svg>
                            </a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>

            </div>
            <div class="tabs__tab" id="tab_3" data-tab-info>
                <table class="table">
                    <thead>
                    <tr>
                        <td>Nom événement</td>
                        <td>Date</td>
                    </tr>
                    </thead>
                    <tbody>

                    {% for representation in user_representations_archived %}
                        <tr>
                            <td data-label="Nom événement">{{ representation.event.name }}</td>
                            <td data-label="Date">{{representation.date}}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>

            </div>
        </div>

    <script src="{% static 'js/Account.js' %}"></script>
{% endblock %}

src/Account/templates/users_display.html
{% extends "default.html" %}

{% block body %}
    <h1 class="title">Gestion des comptes</h1>
    <table class="table">
        <thead>
            <tr>
            <td>Nom et prénom</td>
            <td>Super Admin</td>
            <td>Date de création</td>
            <td>Activé</td>
            </tr>
        </thead>
        <tbody>
            {% for user in all_users%}
            <tr>
            <td data-label="Nom et prénom">{{user.first_name}} {{user.last_name}}</td>
            {% if user.is_staff %}
            <td data-label="Super Admin">
                <a href="{% url 'Account:update_admin' user.id %}" class="table-svg ok"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-check-circle" viewBox="0 0 16 16">
                    <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                    <path d="M10.97 4.97a.235.235 0 0 0-.02.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-1.071-1.05z"/>
        </svg></a>
            </td>
            {% else %}
            <td data-label="Super Admin">
                <a href="{% url 'Account:update_admin' user.id %}" class="table-svg ko"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-circle" viewBox="0 0 16 16">
                    <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                    <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
        </svg></a>
            </td>
            {% endif %}
            <td data-label="Date de création">{{ user.date_joined|date:"d F Y" }}</td>
            {% if user.is_active %}
            <td data-label="Activé">
                <a href="{% url 'Account:update_archive' user.id %}" class="table-svg ok"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-check-circle" viewBox="0 0 16 16">
                <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                <path d="M10.97 4.97a.235.235 0 0 0-.02.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-1.071-1.05z"/>
        </svg></a>
            </td>
            {% else %}
            <td data-label="Activé">
                <a href="{% url 'Account:update_archive' user.id %}" class="table-svg ko"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-circle" viewBox="0 0 16 16">
                <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
        </svg></a>
            </td>
            {% endif %}
            </tr>
            {% endfor %}
        </tbody>

    </table>
{% endblock %}