src/CollegeBook/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.triggers.cron import CronTrigger
from Event.tasks import check_event_is_archived, send_remainders_mail, send_thanks_mail, check_rep_is_archived

from . import settings

urlpatterns = [
                  path('', include("Event.urls")),
                  path('admin/', admin.site.urls),
                  path('account/', include("Account.urls")),
                  path('configuration/', include("Configuration.urls")),
                  path('reservation/', include("Reservation.urls")),
                  path('payment/', include("Payment.urls")),
                  path('validation/', include('Validation.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

print("setup tasks")
scheduler = BackgroundScheduler()
scheduler.add_job(check_rep_is_archived, CronTrigger.from_crontab('* * * * *'))
scheduler.add_job(check_event_is_archived, CronTrigger.from_crontab('* * * * *'))  # Exécute toutes les minutes
scheduler.add_job(send_remainders_mail, CronTrigger.from_crontab('0 2 * * *'))  # Exécute toutes les minutes
scheduler.add_job(send_thanks_mail, CronTrigger.from_crontab('0 2 * * *'))  # Exécute toutes les minutes
scheduler.start()

src/Configuration/urls.py
from django.urls import path
from .views import *

app_name = 'Config'
urlpatterns = [
    path('', area_configuration, name="Configuration"),
    path('create_json/', create_json, name="create_json"),
    path('get_place_types/<str:config_name>/', get_place_types, name="get_place_types"),
]

src/Event/urls.py
from django.urls import path
from .views import *

app_name = 'Event'
urlpatterns = [
    path('', events_display, name='display'),
    path('details/<int:even_id>/', event_details, name='details'),
    path('creation/', event_creation, name='creation'),
    path('delete_representation/<int:representation_id>/', delete_representation, name="delete_representation"),
    path('update_event/<int:event_id>/', event_update, name='update'),
    path('publish_event/<int:event_id>/', publish_event, name='publish_event'),
    path('delete_event_draft/<int:event_id>/', delete_event_draft, name='delete_draft')
]

src/Reservation/urls.py
from django.urls import path
from .views import *

app_name = 'Reservation'
urlpatterns = [
    path('seat_selection/<int:representation_id>/', seat_selection, name="seat_selection"),
    path('representation_reservation/<int:representation_id>/', representation_reservation, name="representation_reservation"),
    path('seat_selection/<int:representation_id>/process_price/', process_price, name="process_price"),
    path('seat_selection/<int:representation_id>/reserve_seats/', reserve_seats, name="check_availability"),
]

src/Event/forms.py
from datetime import datetime

from django import forms

from tagify.fields import TagField, TagInput

from CollegeBook.utils import clean_tagify_string
from Event.models import Event, Representation, Price, CodePromo


class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = [
            'name',
            'image',
            'description',
            'duration',
            'user',
            'configuration',
            'artiste',

        ]
        labels = {'name': 'Nom de l\'événement', 'duration': 'Durée', 'description': 'Description',
                  'image': 'Illustration', 'user': 'Organisateurs',
                  'configuration': 'Configuration', 'artiste': 'Artistes'}
        widgets = {'duration': forms.TimeInput(attrs={'class': 'Time'})}

    date = forms.CharField(label='Date de l\'événement', widget=forms.TextInput(attrs={'class': 'MultiDate'}))

    drink_price = forms.FloatField(label='Prix des tickets boisson', min_value=0,
                                   widget=forms.NumberInput(attrs={"step": '0.01'}))

    food_price = forms.FloatField(label='Prix des tickets nourriture', min_value=0,
                                  widget=forms.NumberInput(attrs={"step": '0.01'}))

    promo_codes = forms.CharField(label='Codes promo', max_length=200, required=False)

    def clean_promo_codes(self, *args, **kwargs):
        data = self.cleaned_data.get("promo_codes")
        name = self.cleaned_data.get("name")
        codes = CodePromo.objects.all()
        for code in codes:
            print(code)
        try:
            event = Event.objects.get(name=name)
            codes = codes.exclude(event_id=event.id)
            for code in codes:
                print(code)
        except Exception:
            pass

        if data != "":
            data = clean_tagify_string(data)
        form_codes = [code.split(":")[0].replace(" ", "") for code in data]

        if codes:
            for code in codes:
                if code.code in form_codes:
                    print("erreur")
                    raise forms.ValidationError(f"Le code promo {code.code} exitse déjà")
        return data

    def clean_artiste(self):
        data = self.cleaned_data["artiste"]
        data = ' ,'.join(clean_tagify_string(data))
        return data

    def save(self, commit=True):
        event = super(EventForm, self).save(commit=False)

        if commit:
            event.save()

            # Representations creation in DB
            for user in self.cleaned_data["user"]:
                event.user.add(user)
            event = Event.objects.get(name=self.cleaned_data['name'])
            dates = self.cleaned_data['date'].split(', ')
            if dates != '':
                for date in dates:
                    date = datetime.strptime(date, '%d-%m-%Y/%H:%M')
                    Representation(date=date, remaining_seats={}, event_id=event.id).save()
                    # TODO remaining_seats

            codes_value = self.cleaned_data["promo_codes"]
            for element in codes_value:
                splitted = element.split(":")
                code_name = splitted[0].split(' ')[0].upper()
                code_amount = splitted[1].split(' ')[1]
                if "€" == code_amount[-1]:
                    CodePromo(code=code_name, amount=code_amount.replace("€", ""), event_id=event.id).save()
                elif "%" == code_amount[-1]:
                    CodePromo(code=code_name, percentage=code_amount.replace("%", ""), event_id=event.id).save()

            # #Prices creation
            drink_price = float(self.cleaned_data["drink_price"])
            food_price = float(self.cleaned_data["food_price"])
            Price.objects.create(type="Boisson", price=drink_price, event_id=event.id).save()

            Price.objects.create(type="Nourriture", price=food_price, event_id=event.id).save()

        return event


class UpdateDateEventForm(forms.Form):
    date = forms.CharField(widget=forms.TextInput(attrs={'class': 'SingleDate'}))


class ConfirmForm(forms.Form):
    CHOICES = [
        ('1', 'OUI'),
        ('2', 'NON'),
    ]
    choice = forms.ChoiceField(widget=forms.RadioSelect, choices=CHOICES)

src/Event/views.py
from datetime import datetime
from pathlib import Path
from datetime import datetime, timedelta
import stripe
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.utils import timezone
from unidecode import unidecode

from CollegeBook.utils import stripe_id_creation
from Configuration.models import Place
from Configuration.views import add_default_configuration
from Event.models import Event, Representation, Config, CodePromo, Price
from .forms import EventForm, ConfirmForm
from Reservation.models import Reservation
from django.core.mail import send_mail
from django.template.loader import render_to_string


def events_display(request):
    all_event = Event.objects.filter(state='ACT')
    return render(request, 'events_display.html', {'all_event': all_event})


def event_details(request, even_id):
    event = Event.objects.get(pk=even_id)
    if event.state != 'ACT':
        return redirect('Event:display')

    representations = Representation.objects.filter(state='ACT', date__gte=timezone.now(), event=event.id)
    return render(request, 'event_details.html', {"event": event, "representations": representations})


@login_required
def event_creation(request):
    if request.method == 'POST':
        form = EventForm(request.POST, request.FILES)
        if form.is_valid():
            try:
                form.save()
                return redirect('Account:events', request.user.id)
            except ValueError as error:

                return render(request, 'error.html', {'error': error})
        configurations = Config.objects.filter(user=request.user.id)
        return render(request, 'event_creation.html', {'form': form, 'configurations': configurations})

    else:
        form = EventForm()
        if not (Config.objects.filter(user=1)):
            add_default_configuration()
        print(request.user.id)
        if request.user.id == 1:
            configurations = Config.objects.filter(user=1)
            print(configurations)
        else:
            configurations_default = Config.objects.filter(user=1)
            configurations_user = Config.objects.filter(user=request.user.id)
            configurations = configurations_default.union(configurations_user)

        return render(request, 'event_creation.html', {'form': form, 'configurations': configurations})


@login_required
def delete_representation(request, representation_id):
    representation = Representation.objects.get(pk=representation_id)
    if representation.date <= timezone.now():
        return redirect('Account:events', request.user.id)
    if request.method == 'POST':

        form = ConfirmForm(request.POST)

        if form.is_valid():
            choice = form.cleaned_data['choice']
            if choice == "1":
                reservations = Reservation.objects.filter(representation=representation)
                for reservation in reservations:
                    date_pdf = reservation.representation.date + timedelta(hours=2)
                    date_pdf = date_pdf.strftime("%d/%m/%Y %H:%M")
                    mail_content = "Nous somme au regret de vous annoncer que la representation de l'evenement %s,  le %s à malheureusement été annulée, vous pouvez contacter l'adresse reservations@cspu.be pour plus d'information " % (
                    reservation.representation.event.name, date_pdf)
                    html = render_to_string('email.html',
                                            {'name': "monsieur/madame %s" % reservation.last_name,
                                             'email': reservation.email,
                                             'content': mail_content,
                                             })
                    send_mail('Reservation Ticket %s' % reservation.representation.event.name,
                              'Vous avez reserver un Ticket pour la representation de %s' % reservation.representation.event.name,
                              'collegebooktest@gmail.com',
                              ['%s' % reservation.email],
                              fail_silently=False,
                              html_message=html
                              )
                rep = Representation.objects.get(pk=representation_id)
                rep.state = "ARC"
                rep.save()

        return redirect('Account:events', request.user.id)
    else:
        form = ConfirmForm()
        event = Representation.objects.get(pk=representation_id)
        return render(request, 'delete_representation.html', {"form": form, "event": event})


@login_required
def event_update(request, event_id):
    if request.method == 'POST':
        event = Event.objects.get(pk=event_id)
        form = EventForm(request.POST, instance=event)
        if form.is_valid():
            event.user.clear()
            Representation.objects.filter(event_id=event.id).delete()
            CodePromo.objects.filter(event_id=event.id).delete()
            Price.objects.filter(event_id=event.id).delete()

            form.save()

        return redirect('Account:events', request.user.id)
    else:
        event = Event.objects.get(pk=event_id)
        representations = Representation.objects.filter(event_id=event.id)
        dates = ""
        for representation in representations:
            dates += representation.date.strftime("%d-%m-%Y/%H:%M, ")
        if dates[-2] == "," and dates[-1] == " ":
            dates = dates[:-2]
        # drink_price = get_stripe_product_price(product_type="boisson", event_name=event.name)
        # food_price = get_stripe_product_price(product_type="nourriture", event_name=event.name)
        drink_price = Price.objects.get(type="Boisson", event_id=event.id).price
        food_price = Price.objects.get(type="Nourriture", event_id=event.id).price
        codes = CodePromo.objects.filter(event_id=event.id)
        promo_codes = ""
        for code in codes:
            promo_codes += str(code) + ","
        if promo_codes:
            if promo_codes[-1] == ",":
                promo_codes = promo_codes[:-1]

        form = EventForm(instance=event, initial={"date": dates, "drink_price": drink_price, "food_price": food_price,
                                                  "promo_codes": promo_codes})
        return render(request, 'event_modification.html', {"form": form, "event": event})


@login_required()
def publish_event(request, event_id):
    event = Event.objects.get(pk=event_id)
    reps = Representation.objects.filter(event=event)
    for rep in reps:
        rep.state = 'ACT'
        rep.save()
    event.state = 'ACT'
    event.save()

    # Create stripe products
    drink_price = Price.objects.get(type="Boisson", event_id=event.id).price
    stripe.Product.create(
        name="Ticket boisson" + " [" + unidecode(event.name) + "]",
        default_price_data={
            'unit_amount': int(drink_price * 100),
            'currency': 'eur'
        },
        id=stripe_id_creation("boisson", unidecode(event.name))
    )

    food_price = Price.objects.get(type="Nourriture", event_id=event.id).price
    stripe.Product.create(
        name="Ticket nourriture" + " [" + unidecode(event.name) + "]",
        default_price_data={
            'unit_amount': int(food_price * 100),
            'currency': 'eur'
        },
        id=stripe_id_creation("nourriture", unidecode(event.name))
    )

    configuration = Config.objects.get(name=event.configuration)
    places = Place.objects.filter(configuration_id=configuration.id)
    for place in places:
        stripe.Product.create(
            name="Siège " + place.type.capitalize() + " [" + unidecode(event.name) + "]",
            default_price_data={
                'unit_amount': int(float(place.price) * 100),
                'currency': 'eur'
            },
            id=stripe_id_creation(place.type, unidecode(event.name))
        )

    # Create 1 room per representation
    event_representations = Representation.objects.filter(event_id=event.id)
    path = Path(__file__).resolve().parent
    srcPath = path.parent
    src_file = srcPath.joinpath("Configuration" + configuration.url_json)

    #TODO
    # if not path.joinpath("static/json/" + event.name).exists():
    #     path.joinpath("static/json/" + event.name).mkdir(parents=True, exist_ok=True)
    # for represent in event_representations:
    #     dst_file = path / "static" / "json" / event.name / str(represent.id)


    if not path.joinpath("static/json/" + unidecode(event.name)).exists():
        path.joinpath("static/json/" + unidecode(event.name)).mkdir(parents=True, exist_ok=True)
    for represent in event_representations:
        dst_file = path / "static" / "json" / unidecode(event.name) / str(represent.id)
        dst_file = dst_file.with_suffix(".json")
        with open(src_file, "rb") as source_file:
            with open(dst_file, "wb") as destination_file:
                destination_file.write(source_file.read())

    promotions = CodePromo.objects.filter(event_id=event.id)
    applies_to = applies_to = [str(stripe_id_creation(element.type, unidecode(event.name))) for element in
                               list(Price.objects.filter(event_id=event.id)) + list(
                                   Place.objects.filter(configuration_id=event.configuration_id))]

    print(applies_to)

    for promotion in promotions:
        coupon_id = stripe_id_creation(promotion.code, unidecode(event.name))
        coupon_name = f"Bon {promotion.code} [{unidecode(event.name)}]"
        if promotion.percentage:
            stripe.Coupon.create(
                id=coupon_id,
                name=coupon_name,
                percent_off=promotion.percentage,
                duration="forever",
                applies_to={"products": applies_to}
            )
        if promotion.amount:
            stripe.Coupon.create(
                id=coupon_id,
                name=coupon_name,

src/Event/templates/defaultEvent.html
{% extends "default.html" %}

{% load static %}

{%  block head %}
    <link rel="stylesheet" href= {% static "css/Event.css" %} >
{% endblock %}

{% block script %}
    <script src="{% static 'js/Event.js' %}"></script>
{% endblock %}

src/Event/templates/delete_representation.html
{% extends "defaultEvent.html" %}

{% block body %}
    <h1 class="title"> Souhaitez vous vraiment supprimer l'event {{event.name}} ?</h1>
    <div class="form">
        <form action="" method="post">
            {% csrf_token %}
            {{ form.choice }}
            <input type="submit" value="Confirmer">
        </form>
    </div>
{% endblock %}

src/Event/templates/event_creation.html
{% extends "defaultEvent.html" %}

{% load static %}

{%  block head %}
    {{ form.media }}
{%  endblock %}

{% block body %}
    <h1 class="title">Création d'événement</h1>
    <div class="form">
        <form action="" method="post" enctype='multipart/form-data'>
            {% csrf_token %}
        
            <div class="input-box">
                <label for="name">Nom</label>
                <input type="text" id="name" name="name">
                <div id="name-errors"></div>
            </div>
            
            <div class="input-box">
                {{ form.image.label }}
                {{ form.image }}
                {{ form.image.errors }}
            </div>
            <div class="input-box">
                {{ form.description.label }}
                {{ form.description }}
                {{ form.description.errors }}
            </div>
            <div class="input-box">
                {{ form.duration.label }}
                {{ form.duration }}
                {{ form.duration.errors }}
            </div>
            <div id="artist" class="input-box">
                <div class="input-button">
                    <div class="input-tag">
                        <label>Ajouter un artiste</label>
                        <input id="text" type="text">
                    </div>

                    <button id="add-button" type="button">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus" viewBox="0 0 16 16">
                            <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
                        </svg>
                    </button>
                </div>
                <div id="artist-div" class="input-button undisplayed">
                    {{ form.artiste }}
                    <button id="del-button" type="button">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
                            <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5ZM11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H2.506a.58.58 0 0 0-.01 0H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1h-.995a.59.59 0 0 0-.01 0H11Zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5h9.916Zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47ZM8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5Z"/>
                        </svg>
                    </button>
                </div>
                {{ form.artiste.errors }}
            </div>
            <div class="input-box">
                {{ form.user.label }}
                {{ form.user }}
                {{ form.user.errors }}
            </div>
            <div class="input-box">
                {{ form.date.label }}
                {{ form.date }}
                {{ form.date.errors }}
            </div>
            <div class="input-box">
                {{form.configuration.label}}
                {{ form.configuration }}
                {{ form.configuration.errors }}
            </div>

            <a href="{% url 'Config:Configuration' %}">Créer une configuration de salle</a>
            <div class="input-box">
                {{ form.drink_price.label }}
                {{ form.drink_price }}
                {{ form.drink_price.errors }}
            </div>
            <div class="input-box">
                {{ form.food_price.label }}
                {{ form.food_price }}
                {{ form.food_price.errors }}
            </div>
            <div id="promo" class="input-box">
                <div class="input-button">
                    <div class="input-tag">
                        <label label="nom">Nom du code promo</label>
                        <input id="nom" type="text">
                    </div>
                    <div id="montant-zone" class="input-tag">
                        <label id="montant-label">Montant du code promo</label>
                        <input id="montant" type="number" step="0.01" min="0.01">
                    </div>
                    <div id="pourcentage-zone" class="input-tag undisplayed">
                        <label id="pourcentage-label">Pourcentage du code promo</label>
                        <input id="pourcentage" type="number" step="1"  min="1" max="100">
                    </div>
                    <div class="radio-divs">
                        <div class="radio">
                            <input type="radio" id="promo_type1" name="promo_type" value="Montant" checked>
                            <label for="promo_type1">Montant</label>
                        </div>
                        <div class="radio">
                            <input type="radio" id="promo_type2" name="promo_type" value="Pourcentage">
                            <label for="promo_type2">Pourcentage</label>
                        </div>
                    </div>
                    <button id="add-button" type="button">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus" viewBox="0 0 16 16">
                          <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
                        </svg>
                    </button>
                </div>
                <div id="promo-div" class="input-button undisplayed">
                    {{ form.promo_codes }}
                    <button id="del-button" type="button">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
                            <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5ZM11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H2.506a.58.58 0 0 0-.01 0H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1h-.995a.59.59 0 0 0-.01 0H11Zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5h9.916Zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47ZM8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5Z"/>
                        </svg>
                    </button>
                </div>

                {{ form.promo_codes.errors }}
            </div>
            <input type="submit" value="Créer l'événement">
        </form>
    </div>
    <script>
        // Récupérer le champ name
        var nameField = document.getElementById("name");
    
        // Ajouter un gestionnaire d'événement pour la saisie de texte
        nameField.addEventListener("input", function() {
            // Récupérer la valeur du champ name
            var nameValue = nameField.value;
    
            // Valider la saisie de texte avec une expression régulière
            var regex = /^[a-zA-Z0-9À-ÿ ]*$/; // Autoriser les lettres majuscules et minuscules, les chiffres et les espaces
            if (!regex.test(nameValue)) {
                // Si la saisie est invalide, afficher un message d'erreur
                document.getElementById("name-errors").innerHTML = "Veuillez saisir uniquement des lettres, des chiffres et des espaces";
            } else {
                // Sinon, effacer les messages d'erreur
                document.getElementById("name-errors").innerHTML = "";
            }
        });
    </script>
{% endblock %}

src/Event/templates/event_details.html
{% extends "defaultEvent.html" %}

{% block body %}
    <div class="event-summary">
        <div class="event-infos">
            <div id="name">
                <h1 class="title">{{ event.name }}</h1>
            </div>
            <div id="description">
                {{ event.description }}
            </div>
            <div id="artiste">
                <strong>Artistes: </strong>{{ event.artiste }}
            </div>
        </div>
        <div class="event-image">
            {% if event.image.url is not null %}
                <img src="{{ event.image.url }}" alt="{{ event.name }}">
            {% endif %}
        </div>
    </div>

    <h2 class="title">Liste des représentations</h2>
    <table class="table">
        <thead>
            <tr>
                <td>Date</td>
                <td>Réserver</td>
            </tr>
        </thead>
        <tbody>
            {% for representation in representations %}
            <tr>
                <td data-label="Date">{{representation.date}}</td>
                <td data-label="Réserver"><a href="{% url 'Reservation:seat_selection' representation.id %}" class="table-svg ok">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bag" viewBox="0 0 16 16">
                      <path d="M8 1a2.5 2.5 0 0 1 2.5 2.5V4h-5v-.5A2.5 2.5 0 0 1 8 1zm3.5 3v-.5a3.5 3.5 0 1 0-7 0V4H1v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V4h-3.5zM2 5h12v9a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V5z"/>
                    </svg>
                </a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

src/Event/templates/events_display.html
{% extends "defaultEvent.html" %}

{% block body %}
    <h1 class="title">Les événements</h1>
    {% for event in all_event %}
        <div class="card mb-3" style="max-width: 100%; height: auto;">
            <div class="row g-0">
                <div class="col-md-3">
                    {% if event.image %}
                        <img class="event-pre-image" src="{{ event.image.url }}" class="img-fluid rounded-start" width="300" height="400"
                             alt="{{ event.name }}">
                    {% endif %}
                </div>
                <div class="col-md-9">
                    <div class="card-body">
                        <h5 class="card-title">{{ event.name }}</h5>
                        <p class="card-text">{{ event.description }}</p>
{#                        <p class="card-text"> Les représentations : <br>#}
{#                            <!-- demander pour savoir ce qu'il préfère-->#}
{#                            {% for representation in all_representation %}#}
{#                                {% if representation.event.id == event.id %}#}
{#                                    {{ representation.date }}#}
{#                                    <br>#}
{#                                {% endif %}#}
{#                            {% endfor %}#}
{#                        </p>#}
                        <p class="card-text"><small class="text-muted">Durée: {{ event.duration }} heures</small></p>
                        <a href="{% url 'Event:details' event.id %}" class="button">Details</a>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}