src/CollegeBook/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.triggers.cron import CronTrigger
from Event.tasks import check_event_is_archived, send_remainders_mail, send_thanks_mail, check_rep_is_archived

from . import settings

urlpatterns = [
                  path('', include("Event.urls")),
                  path('admin/', admin.site.urls),
                  path('account/', include("Account.urls")),
                  path('configuration/', include("Configuration.urls")),
                  path('reservation/', include("Reservation.urls")),
                  path('payment/', include("Payment.urls")),
                  path('validation/', include('Validation.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

print("setup tasks")
scheduler = BackgroundScheduler()
scheduler.add_job(check_rep_is_archived, CronTrigger.from_crontab('* * * * *'))
scheduler.add_job(check_event_is_archived, CronTrigger.from_crontab('* * * * *'))  # Exécute toutes les minutes
scheduler.add_job(send_remainders_mail, CronTrigger.from_crontab('0 2 * * *'))  # Exécute toutes les minutes
scheduler.add_job(send_thanks_mail, CronTrigger.from_crontab('0 2 * * *'))  # Exécute toutes les minutes
scheduler.start()

src/Event/urls.py
from django.urls import path
from .views import *

app_name = 'Event'
urlpatterns = [
    path('', events_display, name='display'),
    path('details/<int:even_id>/', event_details, name='details'),
    path('creation/', event_creation, name='creation'),
    path('delete_representation/<int:representation_id>/', delete_representation, name="delete_representation"),
    path('update_event/<int:event_id>/', event_update, name='update'),
    path('publish_event/<int:event_id>/', publish_event, name='publish_event'),
    path('delete_event_draft/<int:event_id>/', delete_event_draft, name='delete_draft')
]

src/Reservation/urls.py
from django.urls import path
from .views import *

app_name = 'Reservation'
urlpatterns = [
    path('seat_selection/<int:representation_id>/', seat_selection, name="seat_selection"),
    path('representation_reservation/<int:representation_id>/', representation_reservation, name="representation_reservation"),
    path('seat_selection/<int:representation_id>/process_price/', process_price, name="process_price"),
    path('seat_selection/<int:representation_id>/reserve_seats/', reserve_seats, name="check_availability"),
]

src/Reservation/models.py
from datetime import datetime
import uuid
from django.db import models

from Configuration.models import Place
from Event.models import Representation

from polymorphic.models import PolymorphicModel


class Reservation(models.Model):
    email = models.EmailField("Adresse mail de la reservation")
    last_name = models.CharField("Nom de la personne qui a réserver", max_length=50)
    first_name = models.CharField("Prénom de la personne qui réserve", max_length=50)
    phone = models.CharField("Numéro de tel de la personne qui réserve", max_length=10)
    date = models.DateTimeField("Date de la réservation", default=datetime.now())
    note = models.CharField("Remarque sur la réservation", max_length=1000, blank= True)
    drink_number = models.IntegerField("Ticket boisson pris avec la réservation", default=0)
    food_number = models.IntegerField("Ticket nourriture pris avec la réservation", default=0)
    paid = models.BooleanField("État du payement", default=False)
    checkout_session = models.CharField("Session du payement", max_length=70, blank=True)

    # price = models.ForeignKey(Price, on_delete=models.CASCADE)

    representation = models.ForeignKey(Representation, on_delete=models.CASCADE)

    def __str__(self):
        return "Reservation de " + self.last_name + " " + self.first_name + " pour le spectacle du " + str(
            self.representation.date)


class AbstractTicket(PolymorphicModel):
    code = models.CharField(primary_key=True, max_length=25)
    qrcode_is_validated = models.BooleanField("vérifie si le qrcode a déjà été scanné", default=False)
    reservation = models.ForeignKey(Reservation, on_delete=models.CASCADE)

    @classmethod
    def create(cls, **kwargs):
        random_id = uuid.uuid4().hex[:25]
        instance = cls(code=random_id, **kwargs)
        instance.save()

        return instance

    @property
    def ticket_type(self) -> str:
        return "debout"

class Ticket(AbstractTicket):
    type = models.ForeignKey(Place, on_delete=models.CASCADE)


class StandingTicket(Ticket):
    pass


class SeatingTicket(Ticket):
    seat_number = models.CharField("Trigramme du siège", max_length=3)

    @property
    def ticket_type(self) -> str:
        return "Assis"

class ExtraTicket(AbstractTicket):
    pass


class FoodTicket(ExtraTicket):
    @property
    def ticket_type(self) -> str:
        return "Nourriture"


class DrinkTicket(ExtraTicket):
    @property
    def ticket_type(self) -> str:
        return "Boisson"

src/Reservation/forms.py
from django import forms

from Configuration.models import Place
from .models import Reservation, Representation, StandingTicket, SeatingTicket, DrinkTicket, FoodTicket


class ReservationForm(forms.ModelForm):
    class Meta:
        model = Reservation
        fields = [
            'email',
            'last_name',
            'first_name',
            'phone',
            'note',
            'drink_number',
            'food_number'
        ]
        labels = {'email': 'Email', 'last_name': 'Nom', 'first_name': 'Prénom', 'phone': 'Numéro de téléphone',
                  'note': 'Commentaire', 'drink_number': 'Tickets boissons', 'food_number': 'Tickets nourriture'}
        widgets = {'drink_number': forms.NumberInput(attrs = {'min' : '0'}), 'food_number': forms.NumberInput(attrs={'min': '0'})}
        field_options = {'note': {'required': False}}
    selectedseat = forms.CharField(label='Place Selectionner', required=True)

    def save(self, representation_id, commit=True):
        reservation = super(ReservationForm, self).save(commit=False)
        if commit:
            reservation.representation = Representation.objects.get(pk=representation_id)
            reservation.save()
            if self.cleaned_data["drink_number"] > 0:
                DrinkTicket.create(reservation_id=reservation.id)
            if self.cleaned_data["food_number"] > 0:
                FoodTicket.create(reservation_id=reservation.id)

            selected_seats = self.cleaned_data["selectedseat"]
            selected_seats_dic = eval(selected_seats)
            # selected_seats = selected_seats.split(",")
            for element in selected_seats_dic.keys():
                type_siege = selected_seats_dic[element].split()[1]
                place = Place.objects.get(type= type_siege,
                                            configuration_id=reservation.representation.event.configuration_id)
                SeatingTicket.create(seat_number=element, type_id=place.id, reservation_id=reservation.id)
        return reservation 

src/Reservation/views.py
from pathlib import Path

import json
import qrcode
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.utils import timezone
from unidecode import unidecode

from CollegeBook.utils import findRowId, findJsonID
from Configuration.models import Place, Config
from Event.models import Representation, Event, Price
from .forms import ReservationForm


def seat_selection(request, representation_id):
    representation = Representation.objects.get(pk=representation_id)
    if representation.state != 'ACT' or representation.date <= timezone.now():
        return redirect('Event:display')
    eventID = representation.event_id
    event = Event.objects.get(pk=eventID)
    configurationID = event.configuration_id
    configuration = Config.objects.get(pk=configurationID)
    url = "/static/json/" + unidecode(event.name) + "/" + str(representation.id) + ".json"


    places = Place.objects.filter(configuration_id=configurationID)
    seatTypes = [place.type for place in places]
    seatTypesJson = json.dumps(seatTypes)

    return render(request, 'seat_selection.html', {"representation": representation, "url": url, "seatTypes":seatTypesJson})


def process_price(request, representation_id):
    selected_seats_str = request.POST.get("selectedSeatsID")
    selected_seats = json.loads(selected_seats_str)
    config = Config.objects.get(pk=Event.objects
                                .get(pk=Representation.objects.
                                     get(pk=representation_id).event.id).configuration.id)
    total_price = 0
    total_standing = 0
    seats_list = []
    for seatIDS in selected_seats:
        seatType = selected_seats[seatIDS].split()[1]
        price = Place.objects.get(configuration_id=config, type=seatType).price
        total_price += price
        if "Debout" not in seatIDS:
            seats_list.append(seatIDS)
        else :
            total_standing += 1

    seats_list = sorted(seats_list)
    if total_standing > 0 :
        seats_list.append("Debout x"+str(total_standing))
    return JsonResponse({'total_price': total_price, 'selected_seats': seats_list})

def reserve_seats(request,representation_id):
    selectedSeatsIDsSTR = request.POST.get("selectedSeatsIDs")
    roomType = request.POST.get("roomType")
    url = request.POST.get("currentRoom")

    seatsReserved = True
    selectedSeatsIDs = json.loads(selectedSeatsIDsSTR)
    if len(list(selectedSeatsIDs.keys())) == 0:
        seatsReserved = False
        return(JsonResponse({'seatsReserved': seatsReserved}))
    path = Path(__file__).resolve().parent.parent
    src_file = path.joinpath("Event" + url)

    with open(src_file,'r') as f:
        data = json.load(f)

    if roomType == "seat" :
        for seatID in selectedSeatsIDs:
            rowID = findRowId(seatID[0])
            columnID = int(seatID[1:])
            i = 0
            while data[i]["class"] != "seat-row":
                rowID +=1
                i+=1
            jsonID = findJsonID(data[rowID]["seat"], columnID)
            if data[rowID]["seat"][jsonID] == "seat sold":
                seatsReserved = False
                return(JsonResponse({'seatsReserved': seatsReserved}))
            else:
                data[rowID]["seat"][jsonID] = "seat sold"
    
    elif roomType == "standing-zone":
        if ("nbr_place" in data[0]):
            remainingPlaces = int(data[0]["nbr_place"])
        elif("nbr_place" in data[1]):
            remainingPlaces = int(data[1]["nbr_place"])

        for i in range(len(selectedSeatsIDs)):
            remainingPlaces -= 1
            if remainingPlaces == -1:
                seatsReserved = False
                return(JsonResponse({'seatsReserved': seatsReserved}))
        if ("nbr_place" in data[0]):
            data[0]["nbr_place"] = remainingPlaces
        elif("nbr_place" in data[1]):
            data[1]["nbr_place"] = remainingPlaces
    
    elif roomType == "standing-zone+seat":
        print("\n\n\nsalutlesnazes")
        if ("nbr_place" in data[0]):
            remainingPlaces = int(data[0]["nbr_place"])
        elif("nbr_place" in data[1]):
            remainingPlaces = int(data[1]["nbr_place"])

        for seatID in selectedSeatsIDs:
            if "Debout" not in seatID :
                rowID = findRowId(seatID[0])
                columnID = int(seatID[1:])
                i = 0
                while data[i]["class"] != "seat-row":
                    rowID +=1
                    i+=1
                jsonID = findJsonID(data[rowID]["seat"], columnID)
                print("\n\n\n",rowID,json)
                if data[rowID]["seat"][jsonID] == "seat sold":
                    seatsReserved = False
                    return(JsonResponse({'seatsReserved': seatsReserved}))
                else:
                    data[rowID]["seat"][jsonID] = "seat sold"
            else:
                remainingPlaces -= 1
                if remainingPlaces == -1:
                    seatsReserved = False
                    return(JsonResponse({'seatsReserved': seatsReserved}))
        if ("nbr_place" in data[0]):
            data[0]["nbr_place"] = remainingPlaces
        elif("nbr_place" in data[1]):
            data[1]["nbr_place"] = remainingPlaces

    with open(src_file,'w') as f:
        json.dump(data,f)
    return(JsonResponse({'seatsReserved': seatsReserved}))
    


def representation_reservation(request, representation_id):
    representation = Representation.objects.get(pk=representation_id)
    if representation.state != 'ACT' or representation.date <= timezone.now():
        return redirect('Event:display')
    if request.method == 'POST':
        form = ReservationForm(request.POST)
        if form.is_valid():
            form.save(representation_id)

            return redirect('Payment:landing', form.instance.pk)

    else:
        form = ReservationForm()
        event_id = Representation.objects.get(pk=representation_id).event
        price_tickets = Price.objects.filter(event=event_id)
        drink_price = price_tickets.get(type="Boisson")
        food_price = price_tickets.get(type="Nourriture")
        place_price = Place.objects.all()
        return render(request, 'representation_reservation.html',
                      {'form': form, 'drink_price': drink_price, 'food_price': food_price, "place_price": place_price})


def makeQrcode():
    data = 'https://www.youtube.com/shorts/SXHMnicI6Pg'
    img = qrcode.make(data)

src/Reservation/templates/defaultReservation.html
{% extends "defaultConfiguration.html" %}

{% load static %}

{%  block head %}
    <link rel="stylesheet" href= {% static "css/Configuration.css" %} >
    <link rel="stylesheet" href= {% static "css/Reservation.css" %} >
{% endblock %}

{% block script %}
    <script src="{% static 'js/Reservation.js' %}"></script>
{% endblock %}

src/Reservation/templates/email.html
<h2>Reservation</h2>

<p><b> Name : </b>{{ name }}</p>
<p><b> Email : </b>{{ email }}</p>
<p><b> Content : </b>{{ content }}</p>

src/Reservation/templates/representation_reservation.html
{% extends "default.html" %}

{% block body %}
    <h1 class="title">Vos informations</h1>
    <div class="form">
        <form action="" method="post" enctype='multipart/form-data'>
            {% csrf_token %}
            <div class="input-box">
                {{ form.email.label }}
                {{ form.email }}
                {{ form.email.errors }}
            </div>
            <div class="input-box">
                {{ form.last_name.label }}
                {{ form.last_name }}
                {{ form.last_name.errors }}
            </div>
            <div class="input-box">
                {{ form.first_name.label }}
                {{ form.first_name }}
                {{ form.first_name.errors }}
            </div>
            <div class="input-box">
                {{ form.phone.label }}
                {{ form.phone }}
                {{ form.phone.errors }}
            </div>
            <div class="input-box">
                {{ form.note.label }}
                {{ form.note }}
                {{ form.note.errors }}
            </div>
            <div class="input-box">
                {{ form.drink_number.label }}
                {{ form.drink_number }}
                {{ form.drink_number.errors }}
            </div>
            <div>  <p>Prix du ticket : {{drink_price.price}}</p>
                   </div>
            <div class="input-box">
                {{ form.food_number.label }}
                {{ form.food_number }}
                {{ form.food_number.errors }}
            </div>
            <div>  <p>Prix du ticket : {{food_price.price}}</p>
            </div>
            <div class="input-box">
{#                <label for="selectedseat">Sièges selectionnés</label>#}
                <input type="text"name="selectedseat" id="id_selectedseat" value="" readonly hidden>
            </div>

            <input type="submit" value="Réserver l'événement">
        </form>
    </div>
    <script>
        var selectedSeatsJSON = sessionStorage.getItem("selectedSeatsIDs"); // Lire la chaîne JSON depuis la mémoire de session
        var selectedSeatsDict = JSON.parse(selectedSeatsJSON); // Convertir la chaîne JSON en dictionnaire JavaScript
        console.log(selectedSeatsDict)
        var selectedSeatsStr = "{" ;

        for (let i = 0; i<Object.keys(selectedSeatsDict).length;i++){
            selectedSeatsStr += "\""+ Object.keys(selectedSeatsDict)[i]+ "\"" + ": " + "\""+selectedSeatsDict[Object.keys(selectedSeatsDict)[i]]+"\"" + ", ";

        }
        // Convertir le dictionnaire en chaîne de caractères
        selectedSeatsStr = selectedSeatsStr.slice(0, -2); // Supprimer la dernière virgule et l'espace
        selectedSeatsStr += "}";
        // Insérer la chaîne de caractères dans le champ de formulaire
        document.getElementById("id_selectedseat").value = selectedSeatsStr;
    </script>
{% endblock %}

src/Reservation/templates/seat_selection.html
{% extends 'defaultReservation.html' %}
{% load static %}


{% block body %}
    <h1 class="title">Choisissez vos places</h1>
    <div id="caption"></div>
    <div class="select-page">
        <div class="full-area">
            <div class="theatre">
                <div class="seat-area">
                </div>

            </div>
        </div>
        <div class="details">
            <div class="details-content">
                <div class="details-text">
                    <h2>Détails de la réservation:</h2>
                    <p id="price">Prix total: </p>
                    <p id="seat-title">Siège(s) sélectionné(s) : </p>
                    <p id="places"> </p>
                </div>
                <a class="button" id="validateButton">Valider</a>
            </div>
        </div>
    </div>

{% endblock %}

{% block script %}
    <script src="{% static 'js/Reservation.js' %}"></script>
    <script>
        const url = "{{url}}";
        const reservationURL = "{% url 'Reservation:representation_reservation' representation.id %}";
        let seatTypes = JSON.parse('{{ seatTypes|safe}}');
        for (let i = 0; i< seatTypes.length;i++){
            seatTypes[i] = "seat "+seatTypes[i].toLowerCase()
        }
        window.addEventListener("load", prepare_json(url));
    </script>
{% endblock %}